version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_catalog
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
      TZ: Europe/Kyiv
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: