spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogdb
    username: catalog
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
     ddl-auto: update
     jdbc:
       time_zone: Europe/Kyiv
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8081
jackson:
  time-zone: Europe/Kyiv